get http://localhost:8080/

####

get http://localhost:8080/api/contacts/12

####

post http://localhost:8080/api/contacts
content-type:application/json

{"name":"gino&geno","number":"3391092384","id":"123"}